name: Linux dotnet release
run-name: ${{ github.actor }} Linux dotnet release
on: 
  workflow_dispatch: 
  push:
   tags:
    - v1.*.*
jobs: 
  linux_dotnet_build_and_release: 
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - run: |
          pip install wget
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh
          pip install -r requirements.txt
          
      - name: Check dotnet
        run: dotnet --info
      
      - name: configure
        run: cmake -S. -Bbuild -DBUILD_DOTNET=ON

      - name: build
        run: cmake --build build

      - name: upload pacakges
        run: 
          cd ./build/dotnet/packages;
          dotnet nuget push lebai.runtime.linux-x64.1.0.*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json;
          dotnet nuget push lebai.1.0.*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json;
