name: Linux dotnet release
run-name: ${{ github.actor }} Linux dotnet release
on: 
  workflow_dispatch: 
  push:
   tags:
    - v1.*.*
jobs: 
  linux_dotnet_build_and_release: 
    runs-on: ubuntu-latest
    container: bitnami/dotnet-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Check dotnet
        run: dotnet --info
      
      - run: |
          apt-get update
          apt-get install -y python3-pip
          pip install -r requirements.txt
      
      - name: configure
        run: cmake -S. -Bbuild -DBUILD_DOTNET=ON

      - name: build
        run: cmake --build build

      - name: upload pacakges
        run: 
          cd ./build/dotnet/packages;
          dotnet nuget push lebai.runtime.linux-x64.1.0.*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json;
          dotnet nuget push lebai.1.0.*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json;
