
name: auditwheel
run-name: ${{ github.actor }} triggered auditwheel
on: 
  workflow_dispatch: 
  push:
  pull_request:
  
jobs:
  compile:
     runs-on: ubuntu-latest
     container: quay.io/pypa/manylinux2010_x86_64
     steps:
       - name: Checkout
         uses: actions/checkout@v1
         
       - run: for PYBIN in /opt/python/*/bin;do "${PYBIN}/pip" install -r requirements.txt; done;
       
       - name: create-wheelhouse-dir
         run: mkdir -p wheelhouse

       - name: build-with-python3.6
         run: |
          rm -rf build
          cmake -S. -Bbuild -DBUILD_PYTHON=ON -DPYTHONPATH=/opt/python/cp36-cp36m
          cmake --build build
          cp build/python/dist/*.whl wheelhouse/
        
       - name: repair-whl
         run: for PYWHL in wheelhouse/*.whl;do auditwheel repair "${PYWHL}";done;
       
       - name: list
         run: ls wheelhouse/
#       - name: upload
#         uses: actions/upload-artifact@v1
#         with:
#          name: build/python/dist/wheelhouse/*.whl
          
