
name: auditwheel
run-name: ${{ github.actor }} triggered auditwheel
on: 
  workflow_dispatch: 
  push: 
  pull_request: 
  
jobs:
  compile:
     runs-on: ubuntu-latest
     container: quay.io/pypa/manylinux2010_x86_64
     steps:
       - name: Checkout
         uses: actions/checkout@v1
         
       - run: for PYBIN in /opt/python/*/bin;do "${PYBIN}/pip" install -r requirements.txt done

       - name: configure
         run: cmake -S. -Bbuild -DBUILD_PYTHON=ON

       - name: build
         run: cmake --build build
        
       - run: cd build/python/dist/
         
       - name: repair
         run: auditwheel repair ./*.whl
        
       - name: upload
         uses: actions/upload-artifact@v3
         with:
          path: ./wheelhouse/*.whl
          
