
name: auditwheel
run-name: ${{ github.actor }} triggered auditwheel
on: 
  workflow_dispatch: 
  push: 
  pull_request: 
  
jobs:
  compile:
     runs-on: ubuntu-latest
     container: quay.io/pypa/manylinux2010_x86_64
     steps:
       - name: Checkout
         uses: actions/checkout@v1
         
       - run: for PYBIN in /opt/python/*/bin;do "${PYBIN}/pip" install -r requirements.txt; done;

       - name: configure
         run: cmake -S. -Bbuild -DBUILD_PYTHON=ON

       - name: build
         run: cmake --build build
         
       - name: repair
         run: for PYWHL in build/python/dist/*.whl;do auditwheel repair "${PYWHL}";done;
        
       - name: upload
         uses: actions/upload-artifact@v2
         with:
          path: build/python/dist/wheelhouse/*.whl
          
