
name: auditwheel
run-name: ${{ github.actor }} triggered auditwheel
on: 
  workflow_dispatch: 
  push: 
  pull_request: 
  
jobs:
  compile:
     runs-on: ubuntu-latest
     container: quay.io/pypa/manylinux2010_x86_64
     steps:
       - name: Checkout
         uses: actions/checkout@v1
         
       - run: for PYBIN in /opt/python/*/bin;do "${PYBIN}/pip" install -r requirements.txt; done;
       - run: /opt/python/cp310-cp310/bin/pip install twine==2.0.0

       - name: configure
         run: cmake -S. -Bbuild -DBUILD_PYTHON=ON

       - name: build
         run: cmake --build build
         
       - name: repair
         run: auditwheel repair build/python/dist/*.whl
        
#       - name: upload
#         uses: actions/upload-artifact@v1
#         with:
#          name: wheelhouse/*.whl
          
       - name: upload Pypi
         run: /opt/python/cp310-cp310/bin/twine upload -u ${{ secrets.USRNAME }} -p ${{ secrets.PASSWD }} wheelhouse/*.whl
